---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: onsdigital/dp-concourse-tools-java

inputs:
  - name: encrypted-file-upload

outputs:
  - name: build

run:
  path: encrypted-file-upload/ci/scripts/build.sh
